# Docker Compose for Splittchen with WebSocket support
# For production use, either:
#  1. Use the official image: ghcr.io/splittchen/splittchen:latest
#  2. Build your own: Replace with 'build: .' and remove 'image:' line
services:
  web:
    image: ghcr.io/splittchen/splittchen:latest  # Official maintainer image
    # Alternatively, build from source:
    # build: .
    # image: splittchen:local
    user: "${DOCKER_USER:-1000}:${DOCKER_GROUP:-1000}"
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    # The container now includes WebSocket support via Flask-SocketIO
    # Using Gunicorn with gevent workers for real-time features
    
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - ${DATA_PATH:-./data}/postgres:/var/lib/postgresql/data
    restart: unless-stopped