blank_issues_enabled: false
contact_links:
  - name: 💬 General Discussion
    url: https://github.com/crazynudelsieb/splittchen/discussions
    about: Ask questions, share ideas, or discuss the project with the community
  - name: 🔒 Security Issue
    url: https://github.com/crazynudelsieb/splittchen/security/advisories/new
    about: Please report security vulnerabilities privately (not public issues)